spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendify-pro?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: America/Chicago
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    root: INFO
    org:
      springframework: ERROR

app:
  email:
    course-welcome:
      dispatch:
        interval:1

